name: flutter_application_1
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.3 # Removed duplicate entry
  cloud_firestore: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/travel.jpg
    - assets/logo1.png
    - assets/hajj10.jpg
    - assets/image5.jpg
    - assets/image7.jpg
    - assets/image12.jpg
    - assets/images.jpg
    - assets/image6.jpg
    - assets/image11.jpg
    - assets/pdf/hajj-guide.pdf
    - assets/pdf/umrah-guide.pdf
